GeneralMagicio/q-acc

src/components/InfoSection.tsx

Issue  : https://qacc.atlassian.net/browse/QACC-46

remove learn more button

---

src/components/Modals/CompleteProfileModal.tsx

Added if condition to show different title for eligible user inside modal for completing profile.

Change modal title for eligible user

---

src/components/Modal.tsx

Error was:
```
ReferenceError: document is not defined
at Modal (./src/components/Modal.tsx:75:20)
digest: "2531129476"
53 |       </div>
54 |     </div>,
> 55 |     document.body,
|     ^
56 |   );
57 | };
```

fix modal error related with hydration

---

src/components/DonarDashboard/DonarSupports.tsx
src/components/DonarDashboard/ProjectSupportTable.tsx
src/services/donation.services.ts

fixing one console error about projectId and removed unused console.log

Fixing looping on My contribution page

---

src/components/ProjectDetail/DonateSection.tsx
src/components/ProjectDetail/ProjectDonateButton.tsx
src/queries/project.query.ts

added logic in project card to handle NFT owner and see progress

---

src/components/DonarDashboard/MyProjects.tsx
src/components/DonarDashboard/RoundCollectedInfo.tsx
src/components/Icons/IconChevronDown.tsx
src/components/Icons/IconChevronUp.tsx

https://qacc.atlassian.net/browse/QACC-187?atlOrigin=eyJpIjoiNzgwM2EwOTExNGJjNGQ4OWJjZmVmZDhkNThmNjY5MDMiLCJwIjoiaiJ9

Add round info to project dashboard

---

src/components/DonatePage/DonatePageBody.tsx

fixed ui for donate page

---

src/components/RoundCountBanner.tsx
src/components/RoundInfoSupporter/RemainingTime.tsx
src/components/RoundInfoSupporter/index.tsx
src/hooks/useFetchRoundDetails.ts
src/hooks/useRemainingTime.ts
src/queries/project.query.ts
src/queries/round.query.ts
src/services/project.service.ts
src/types/round.type.ts

https://qacc.atlassian.net/browse/QACC-203?atlOrigin=eyJpIjoiN2U3OTEzZTBiMjU1NDZhOWJkNGU0NmJjNDRkMTAyOWEiLCJwIjoiaiJ9

Add new round query

---

next.config.mjs
src/helpers/image.ts

https://qacc.atlassian.net/browse/QACC-209?atlOrigin=eyJpIjoiZWMzYTY5MWNjYjNlNDlkZmI0NjRmOWQ3ZmYxMGRhYTMiLCJwIjoiaiJ9

migrate to pinata gateway

---

next.config.mjs
src/components/DonatePage/DonatePageBody.tsx

Once when user clicked accepting terms value would be saved. That value also depends does user went throw Provide process.

Changing terms and condition handle

---

src/components/DonarDashboard/DonarSupports.tsx

https://qacc.atlassian.net/browse/QACC-212?atlOrigin=eyJpIjoiZDAzMzU0NWJiMjMxNDRhMmE2MTRhNmY2OWFmY2UyY2MiLCJwIjoiaiJ9

add blank message

---

src/components/DonarDashboard/RoundCollectHeader.tsx
src/components/DonarDashboard/RoundCollectedInfo.tsx

https://qacc.atlassian.net/browse/QACC-242

removed tooltip and copy change

---

src/components/DonarDashboard/RoundCollectHeader.tsx
src/helpers/round.ts
src/queries/round.query.ts
src/types/round.type.ts

Merged after https://github.com/GeneralMagicio/QAcc-BE/pull/89

Renamed variables according to update

---

src/app/page.tsx
src/components/FeaturedProjects/index.tsx

https://qacc.atlassian.net/browse/QACC-247?atlOrigin=eyJpIjoiYjBmMzhmMDlmNDRmNDNmYWI3YmZjMjFkMzIwYzlhZjEiLCJwIjoiaiJ9

Change copy related to qf round

---

src/components/DonarDashboard/ProjectSupportTable.tsx
src/components/DonarDashboard/ProjectUserDonationTable.tsx
src/components/DonatePage/DonateSuccessPage.tsx

https://qacc.atlassian.net/browse/QACC-259

checked null values before showing in table

---

src/app/page.tsx
src/components/FeaturedProjects/index.tsx

https://qacc.atlassian.net/browse/QACC-256

changed texts based on round

---

src/components/DonarDashboard/DonarSuppotedProjects.tsx
src/components/DonarDashboard/MyProjects.tsx
src/components/DonatePage/DonatePageBody.tsx
src/components/ProjectDetail/ProjectDetail.tsx

https://qacc.atlassian.net/browse/QACC-273
https://qacc.atlassian.net/browse/QACC-281

changed project address to issuanceTokenAddress and added link

---

src/components/DonarDashboard/DonarSuppotedProjects.tsx

https://qacc.atlassian.net/browse/QACC-290?atlOrigin=eyJpIjoiMDg1ZWRiMmVlOWZhNGFiMGI0YmY2NGIwM2FiMzE5YzYiLCJwIjoiaiJ9

format token amount

---

src/components/DonarDashboard/DonarSupportedProjects.tsx
src/components/DonarDashboard/DonarSupports.tsx
src/components/DonarDashboard/ProjectUserDonationTable.tsx
src/components/DonarDashboard/RewardsBreakDown.tsx
src/helpers/donation.ts

https://qacc.atlassian.net/browse/QACC-297?atlOrigin=eyJpIjoiMjY1Y2E3OTQ3NjYyNDA3YTgxNGIwODIyMzA1MzI0YzQiLCJwIjoiaiJ9

Handle numbers

---

src/components/Create/CreateProjectForm/index.tsx
src/components/Create/CreateView.tsx
src/hooks/useFetchProjectsCountByUserId.ts
src/queries/project.query.ts
src/services/project.service.ts

https://qacc.atlassian.net/browse/QACC-295?atlOrigin=eyJpIjoiMDI5NjI2MjFhNjBkNGExNGE4NDM4NmI4YTU1M2Y3NDUiLCJwIjoiaiJ9

Prevent user to create multiple projects

---

src/components/DonatePage/DonatePageBody.tsx

https://qacc.atlassian.net/browse/QACC-288

Fix donation cap

---

src/components/DonatePage/DonatePageBody.tsx

https://qacc.atlassian.net/browse/QACC-304

fixed amount by rounding

---

src/app/page.tsx
src/components/DonatePage/DonatePageBody.tsx
src/components/FlashMessage.tsx
src/components/RoundCountBanner.tsx
src/components/RoundInfoSupporter/index.tsx
src/services/donation.services.ts

https://qacc.atlassian.net/browse/QACC-310
https://qacc.atlassian.net/browse/QACC-314

 fixed donation cap error and copy change

---

src/components/Create/CreateTeamForm/index.tsx
src/components/Modals/CreateProjectModal.tsx

https://qacc.atlassian.net/browse/QACC-308

added project success modal

---

src/components/Create/CreateView.tsx

https://docs.google.com/document/d/1-N89TsrajDdZoipkA2lxT3hHo5kluA5xBil6Zbpj7sA/edit?tab=t.0

copy changes

---

src/app/layout.tsx
src/components/ConnectButton/ConnectButton.tsx
src/components/ConnectModal.tsx
src/components/KycLandingButton.tsx
src/config/development.ts
src/config/production.ts
src/config/wagmi.ts
src/context/wagmi.tsx
src/helpers/generateJWT.ts
src/helpers/token.ts
src/types/config.type.ts

Reverts GeneralMagicio/q-acc#306

Revert "Revert back to web3modal"

---

src/components/EditForm/EditProjectForm/index.tsx

https://qacc.atlassian.net/browse/QACC-386

changed name from twitter to X

---

src/components/DonatePage/DonatePageBody.tsx
src/components/Modal.tsx
src/components/Modals/TermsConditionModal.tsx

https://qacc.atlassian.net/browse/QACC-392

added terms and condition modal

---

src/components/DonatePage/DonatePageBody.tsx
src/components/Modals/GitcoinEligibilityModal.tsx
src/components/Modals/ZkidEligibilityModal.tsx
src/config/development.ts
src/config/production.ts
src/types/config.type.ts

https://qacc.atlassian.net/browse/QACC-393
https://qacc.atlassian.net/browse/QACC-380

Copy change modals

---

src/components/DonatePage/DonatePageBody.tsx
src/components/Modals/TermsConditionModal.tsx

https://qacc.atlassian.net/browse/QACC-396

continued donate flow after TOS is accepted

---

src/components/RichTextViewer.tsx

https://qacc.atlassian.net/browse/QACC-394

change max widht of editor to 700px

---

src/components/DonarDashboard/DonarSupportedProjects.tsx
src/components/DonarDashboard/RewardsBreakDown.tsx

https://qacc.atlassian.net/browse/QACC-337
https://qacc.atlassian.net/browse/QACC-403

grayed out claim button and added tooltip to locked and availabe to claim

---

src/components/ProjectCard/ProjectHoverCard.tsx

https://qacc.atlassian.net/browse/QACC-400

hide progress bar in project cards

---

src/components/DonatePage/DonatePageBody.tsx
src/components/DonatePage/EligibilityCheckToast.tsx
src/config/configuration.ts
src/queries/round.query.ts
src/types/round.type.ts

https://qacc.atlassian.net/browse/QACC-398
https://qacc.atlassian.net/browse/QACC-404

copy changes in high cap and low cap

---

src/components/DonatePage/DonatePageBody.tsx

https://qacc.atlassian.net/browse/QACC-402

restrict use to input amount over the cumulativeUSDCapPerUserPerProject

---

src/components/DonatePage/DonatePageBody.tsx
src/components/DonatePage/EligibilityCheckToast.tsx

https://qacc.atlassian.net/browse/QACC-397

show zkid modal if unverified user enters amount above 1000

---

src/app/project/[projectSlug]/page.tsx
src/components/DonatePage/DonatePageBody.tsx
src/components/Rules.tsx

https://qacc.atlassian.net/browse/QACC-416
https://qacc.atlassian.net/browse/QACC-414

made copy changes and

---

src/components/Header/VerificationBanner.tsx
src/components/Header/index.tsx

https://qacc.atlassian.net/browse/QACC-413

added verification banner on all page

---

src/components/RoundInfoBanner/MatchingRoundCard.tsx
src/components/RoundInfoBanner/RemainingTimeBox.tsx
src/components/RoundInfoBanner/RoundStatusBanner.tsx

https://qacc.atlassian.net/browse/QACC-420

added matching pool banner

---

src/components/DonatePage/DonatePageBody.tsx

https://qacc.atlassian.net/browse/QACC-421

 added new functionaly on percentage click

---

src/components/DonarDashboard/MyProjects.tsx
src/components/DonatePage/DonatePageBody.tsx
src/components/DonatePage/DonateSuccessPage.tsx
src/components/Modals/ShareProjectModal.tsx
tailwind.config.ts

https://qacc.atlassian.net/browse/QACC-424
https://qacc.atlassian.net/browse/QACC-423

added share message and added in success page

---

src/app/page.tsx
src/components/QaccRoundEndBanner.tsx
src/config/configuration.ts

https://qacc.atlassian.net/browse/QACC-409

Qacc end banner

---

src/components/ProjectCard/ProjectHoverCard.tsx

https://qacc.atlassian.net/browse/QACC-411

made ui changes in the project card after allocation

---

src/components/ProjectCard/ProjectHoverCard.tsx

https://qacc.atlassian.net/browse/QACC-431

added tootltip to project card

---

src/app/page.tsx
src/components/OnBoardButton.tsx
src/components/QaccRoundEndBanner.tsx
src/components/QaccRoundStats.tsx
src/hooks/useFetchQaccStats.ts
src/queries/round.query.ts
src/services/round.services.ts
src/types/round.type.ts
tailwind.config.ts

https://qacc.atlassian.net/browse/QACC-435

show qacc round stats

---

src/components/ConnectButton/ConnectButton.tsx
src/components/Controllers/UserController.tsx
src/helpers/generateJWT.ts
src/hooks/useSignUser.ts

Reverts GeneralMagicio/q-acc#401

Revert "change local storage to session storage"

---

src/config/production.ts

Reverts GeneralMagicio/q-acc#437

Revert "Feat/production-privado-polygon"
